photos/urls.py
from django.urls import path, re_path
from . import views

app_name = 'photos'
urlpatterns = [
    path('<int:photo_id>/', views.detail, name='detail'),
    re_path(r'^upload/$', views.create, name='create'),
    # path('uploads/', views.create, name='create'),

    path('', views.index, name='list'),
    path('delete/', views.delete, name='delete'),
]

pystargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photos.urls')),
    path('accounts/login/', auth_views.login, name='login',
         kwargs={'template_name': 'accounts/login.html'}),
    path('accounts/logout/', auth_views.logout, name='logout',
         kwargs={'next_page': settings.LOGIN_URL}),
]

urlpatterns += static('upload_files', document_root=settings.MEDIA_ROOT)

photos/models.py
from django.conf import settings
from django.db import models


class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/orig')
    filtered_image = models.ImageField(upload_to='uploads/%Y/%m/%d/filtered', blank=True)
    content = models.TextField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Photo, self).delete(*args, **kwargs)

photos/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Photo
        fields = ('image', 'content', )

photos/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from .models import Photo
from .forms import PhotoForm


def detail(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    context = dict()
    context['photo'] = photo

    return render(request, 'photos/detail.html', context)


def create(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)

    if request.method == 'GET':
        form = PhotoForm()
    elif request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            return redirect('photos:detail', pk=photo.pk)
    context = {
        'photo_form': form
    }
    return render(request, 'photos/edit.html', context)


def index(request):
    photos = Photo.objects.all().order_by('-pk')
    context = dict()
    context['photos'] = photos

    return render(request, 'photos/list.html', context)


def delete(request):
    if request.method=='POST':
        photo_id =request.POST['pk']
        try:
            photo=Photo.objects.get(pk=photo_id, user=request.user)

        except:
            return redirect('photos:detail', pk=photo_id)
        photo.delete()
    return redirect('photos:list')

templates/accounts/login.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <div class="header clearfix">
            <form method="POST" action="{% url 'login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <p>
                        <label for="id_username">Username:</label>
                        <input class="form-control" type="text" name="username" autofocus="" maxlength="254" required="" id="id_username">
                    </p>
                    <p>
                        <label for="id_password">Password:</label>
                        <input class="form-control" type="password" name="password" required="" id="id_password">
                    </p>
                </div>
                <button class="btn btn-block btn-default" type="submit">로그인</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/base/footer.html
<footer class="footer">
    <div class="container">
        <h1 style="text-align:center;">footer</h1>
    </div>
</footer>

templates/base/header.html
<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'photos:list' %}">SDFW</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">로그아웃</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">로그인</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Web Developer for Web</title>
    <link rel="stylesheet" href="/static/bootstrap2.min.css">
</head>
<body>
    {% include 'base/header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'base/footer.html' %}
</body>
</html>

templates/photos/detail.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">

        <div class="col-md-12">
            <h1>{{ photo.pk }}번 사진 보여줄게요</h1>
            <h3>주소는 {{ photo.image.url|truncatechars:40 }}</h3>
            <img src="{{ photo.image.url }}" class="img-thumbnail"/>
            <form method="POST" action="{% url 'photos:delete' %}" class="form-group">
                {% csrf_token %}
                <input type="hidden" name="photo_id" value="{{ photo.pk }}">
                <button class="btn btn-default btn-block" type="submit">삭제</button>
            </form>
        </div>

    </div>
{% endblock %}

templates/photos/edit.html
{% extends 'index.html' %}

{% block content %}

    <div class="container">
        <form method="POST" action="" class="form-group" enctype="multipart/form-data">
            {% csrf_token %}
            {{ photo_form.as_p }}
            <p>
                <button class="btn btn-default btn-block" type="submit">저장</button>
            </p>
        </form>
    </div>

{% endblock %}

templates/photos/list.html
{% extends 'index.html' %}

{% block content %}



<div class="container">
    <div class="row">
        <div class="">
            {% if request.user.is_authenticated %}
                <a class="btn btn-default" role="button" href="{% url 'photos:create' %}">사진 올리기</a>
            {% endif %}
        </div>

        {% for photo in photos %}
        <div class="col-md-4">
            <a href="{% url 'photos:detail' photo_id=photo.pk %}">
                <img src="{{ photo.image.url }}"  class="img-thumbnail img-responsive">
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}